gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 604800
    ttl_update: false
    single_use: true
    cookie:
        enabled: true
        same_site: strict
        secure: '%env(bool:JWT_REFRESH_COOKIE_SECURE)%'
        http_only: true
        path: /
        remove_token_from_body: true

when@dev:
    gesdinet_jwt_refresh_token:
        cookie:
            secure: false

when@test:
    gesdinet_jwt_refresh_token:
        cookie:
            secure: false
